services:
  app:
    container_name: getCabsyApp
    build:
      context: ./
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always
    networks:
      - cabsy-net

  db:
    image: postgres:16.3
    container_name: getCabsyDatabase
    environment:
      POSTGRES_DB: getcabsydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    networks:
      - cabsy-net

networks:
  cabsy-net:
    driver: bridge

volumes:
  db_data:
